### ISSUE TITLE
Hacking SIM cards

### ISSUE THREAD

**Issue by masterT** [CFI-UL/suggestion-box#6]
https://simhacks.github.io/sim-cards/

- buy SIM cards
- buy SIM card reader

**Comment by Anthony00105** [comment]
Bypass,

**Comment by Anthony00105** [comment]
If you could please help me jailvrake my son card so I can have service on my phone I would be greatful and thankful I hope you have a Mary Christmas

**Comment by Anthony00105** [comment]
Can you please hack my SIM card

**Comment by Corb3nik** [comment]
no.

**Comment by Anthony00105** [comment]
Okay sorry

**Comment by Anthony00105** [comment]
Sorry for asking
